---
##ansible-playbook node.yml -i dockerhosts

- hosts: dockerhosts
  remote_user: ec2-user

  tasks:

  - name: start hybris cluster
    shell: sudo ./startAccClusterWithLB.sh
    args: 
        chdir: ~/Scenarios/Accelerator